## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Situation
0,0,Grand Gaube,-20.0064,57.6608,70.38,77,8,3.00,MU,clear sky
1,1,Dikson,73.5069,80.5464,18.07,89,100,8.86,RU,overcast clouds
2,2,Maralal,1.0968,36.6980,59.38,86,95,6.51,KE,light rain
3,3,Tasiilaq,65.6145,-37.6368,37.56,99,100,13.47,GL,moderate rain
4,4,Sturgeon Falls,46.3646,-79.9326,50.05,83,88,6.22,CA,overcast clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
Minimum_Temp=float(input("What is the minimum temperature you would like for your trip? "))
Maximum_Temp=float(input("What is the maximum temperature you would like for your trip? "))

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df=city_data_df.loc[(city_data_df["Max Temp"]<=Maximum_Temp) &\
                               (city_data_df["Max Temp"]>=Minimum_Temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Situation
25,25,Urumqi,43.8010,87.6005,29.35,80,0,0.00,CN,clear sky
27,27,Kharp,66.8014,65.8081,21.45,97,100,1.97,RU,overcast clouds
34,34,Iqaluit,63.7506,-68.5145,22.73,80,100,12.66,CA,light snow
39,39,Longyearbyen,78.2186,15.6401,24.64,68,20,6.91,SJ,few clouds
47,47,Kargasok,59.0556,80.8572,21.78,89,26,7.07,RU,scattered clouds
58,58,Kangaatsiaq,68.3065,-53.4641,31.96,94,100,6.55,GL,light snow
85,85,Husavik,66.0449,-17.3389,30.29,79,70,12.17,IS,broken clouds
89,89,Narsaq,60.9167,-46.0500,26.82,74,32,7.92,GL,scattered clouds
105,105,Paamiut,61.9940,-49.6678,33.13,97,100,11.70,GL,snow
141,141,Atbasar,51.8000,68.3333,25.12,88,97,6.46,KZ,overcast clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID              57
City                 57
Lat                  57
Lng                  57
Max Temp             57
Humidity             57
Cloudiness           57
Wind Speed           57
Country              57
Current Situation    57
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_travel_cities=preferred_cities_df.dropna()
clean_travel_cities.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Situation
25,25,Urumqi,43.8010,87.6005,29.35,80,0,0.00,CN,clear sky
27,27,Kharp,66.8014,65.8081,21.45,97,100,1.97,RU,overcast clouds
34,34,Iqaluit,63.7506,-68.5145,22.73,80,100,12.66,CA,light snow
39,39,Longyearbyen,78.2186,15.6401,24.64,68,20,6.91,SJ,few clouds
47,47,Kargasok,59.0556,80.8572,21.78,89,26,7.07,RU,scattered clouds
58,58,Kangaatsiaq,68.3065,-53.4641,31.96,94,100,6.55,GL,light snow
85,85,Husavik,66.0449,-17.3389,30.29,79,70,12.17,IS,broken clouds
89,89,Narsaq,60.9167,-46.0500,26.82,74,32,7.92,GL,scattered clouds
105,105,Paamiut,61.9940,-49.6678,33.13,97,100,11.70,GL,snow
141,141,Atbasar,51.8000,68.3333,25.12,88,97,6.46,KZ,overcast clouds

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_travel_cities[["City", "Country", "Max Temp", "Current Situation", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Situation,Lat,Lng,Hotel Name
25,Urumqi,CN,29.35,clear sky,43.8010,87.6005,
27,Kharp,RU,21.45,overcast clouds,66.8014,65.8081,
34,Iqaluit,CA,22.73,light snow,63.7506,-68.5145,
39,Longyearbyen,SJ,24.64,few clouds,78.2186,15.6401,
47,Kargasok,RU,21.78,scattered clouds,59.0556,80.8572,
58,Kangaatsiaq,GL,31.96,light snow,68.3065,-53.4641,
85,Husavik,IS,30.29,broken clouds,66.0449,-17.3389,
89,Narsaq,GL,26.82,scattered clouds,60.9167,-46.0500,
105,Paamiut,GL,33.13,snow,61.9940,-49.6678,
141,Atbasar,KZ,25.12,overcast clouds,51.8000,68.3333,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
import json
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index,row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat=row["Lat"]
    lng=row["Lng"]
    
    params["location"]=f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index,"Hotel Name"]=hotels["results"][0]["name"]
        
    except (IndexError):
            print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [9]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.loc[(hotel_df["Hotel Name"]!='')]
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Situation,Lat,Lng,Hotel Name
25,Urumqi,CN,29.35,clear sky,43.8010,87.6005,Hua Ling Grand Hotel Urumqi
27,Kharp,RU,21.45,overcast clouds,66.8014,65.8081,"Hotel ""Sob"""
34,Iqaluit,CA,22.73,light snow,63.7506,-68.5145,Frobisher Inn
39,Longyearbyen,SJ,24.64,few clouds,78.2186,15.6401,"Radisson Blu Polar Hotel, Spitsbergen"
47,Kargasok,RU,21.78,scattered clouds,59.0556,80.8572,Hotel Kargasok
58,Kangaatsiaq,GL,31.96,light snow,68.3065,-53.4641,Nukissiorfiit
85,Husavik,IS,30.29,broken clouds,66.0449,-17.3389,Bjarnabúð
89,Narsaq,GL,26.82,scattered clouds,60.9167,-46.0500,Sleep In Narsaq
105,Paamiut,GL,33.13,snow,61.9940,-49.6678,Pistut
141,Atbasar,KZ,25.12,overcast clouds,51.8000,68.3333,Гостиничный Комплекс Saad

In [10]:
# 8a. Create the output File (CSV)
output_data_file="WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Current Situation</dt><dd>{Current Situation} °F</dd>
</dl>

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))